### ISSUE TITLE
Script de criação

### ISSUE THREAD

**Issue by CarlosZoft** [SBD1/grupo11-Universo-Marvel#11]
Herick :

-- CREATE TABLE obstaculo ();

-- CREATE TABLE personagem ();

-- CREATE TABLE planeta ();

-- CREATE TABLE posse ();

Carlos : 

-- CREATE TABLE recompensa ();

-- CREATE TABLE traje ();

-- CREATE TABLE troca ();

Helena :

-- CREATE TABLE trocavel ();

-- CREATE TABLE viagem ();

-- CREATE TABLE vilao ();

**Comment by hericklima22** [comment]
Script criado.
