### ISSUE TITLE
Script de inserção

### ISSUE THREAD

**Issue by CarlosZoft** [SBD1/grupo11-Universo-Marvel#12]

**Comment by hericklima22** [comment]
Divisão dos MOCKS das tabelas.

HERICK:

acesso_equipamento
arma
base
joia
luta
heroi
vilao

PEDRO:

imunidade_vilao
instancia_heroi
instancia_vilao
mapa
item
instancia_item
viagem

CARLOS:

imunidade_traje
coletavel
consumivel
consumo
efeito
efeito_arma
trocavel

JULIO:

efeito_vilao
equipamento
espaco_vazio
estoque
moeda
nivel
viagem

HELENA:

personagem
posse
rastro
recompensa
traje
troca
